---
# tasks file for aws

- name: "Launching an AWS instance for Kubernetes Master"
  ec2:
       key_name: "{{ key_pair }}"
       instance_type: "{{ instance_type }}"
       image: "{{ image }}"
       wait: yes
       count: 1
       instance_tags:
         Name: "K8s-Master"
       vpc_subnet_id : "{{ subnet_id }}"
       assign_public_ip: yes
       state: present
       region: "{{ region }}"
       group_id: "{{ security_group_id }}"
       aws_access_key: "{{ access_key }}"
       aws_secret_key: "{{ secret_key }}"
  register: control

- debug: 
       msg: "Successfully launched Master"

- name: "Launching AWS instances for Kubernetes Worker Nodes"
  ec2:
       key_name: "{{ key_pair }}"
       instance_type: "{{ instance_type }}"
       image: "{{ image }}"
       wait: yes
       count: 2
       instance_tags:
         Name: "K8s-WorkerNodes"
       vpc_subnet_id : "{{ subnet_id }}"
       assign_public_ip: yes
       state: present
       region: "{{ region }}"
       group_id: "{{ security_group_id }}"
       aws_access_key: "{{ access_key }}"
       aws_secret_key: "{{ secret_key }}"
  register: worker

- debug:
       msg: "Successfully launched WorkerNodes"
